### ISSUE TITLE
The error of predictor_keypointnet.py

### ISSUE THREAD

**Issue by zwy1996** [eliphatfs/SkeletonMerger#1]
Hi, nice job

I am very sorry to bother you, when I ran the predictor_keypointnet.py on the guitar category, I met the following error:
99%|█████████▉| 696/704 [03:42<00:02,  3.12it/s]
Traceback (most recent call last):
  recon, key_points, kpa, emb, null_activation = net(torch.Tensor(np.array(Q)).to(ns.device))
x = batch_norm(x)     merger_net.py", line 35, in forward
ValueError: expected 2D or 3D input (got 1D input)

Thank you very much!

**Comment by eliphatfs** [comment]
There seems to be something wrong on the edge case where a batch (the last batch) only contains 1 element. For a quick workaround you may try a different batch size. Will look into this soon.

**Comment by eliphatfs** [comment]
The problem should have been fixed by #3. If you still encounter the same problem please open a new issue.
