### ISSUE TITLE
Hi, may I ask if you can provide all the Subclass label IDs to train on?

### ISSUE THREAD

**Issue by chenzy9738** [eliphatfs/SkeletonMerger#14]
I checked the KeypointNet and ShapeNetCore datasets, but couldn't find the corresponding SubClass IDs. I only know that Chair corresponds to 14 and Airplane corresponds to 0

I would greatly appreciate it if you could provide all the Subclass label IDs to train on, or tell me how to obtain them!

**Comment by eliphatfs** [comment]
Sorry, I haven't been working on this for so long that I have forgot these details. But I think there is a classes.txt in the dataset that tells you the category IDs. In the worst case you may also visualize one of the point clouds in each category to see the class.

**Comment by chenzy9738** [comment]
Okay, I'll try visualizing it. Thank you very much!
