### ISSUE TITLE
The subclass id of Airplanes and  Guitars ?

### ISSUE THREAD

**Issue by zwy1996** [eliphatfs/SkeletonMerger#5]
Hi, nice job!

I have noticed that you changed the subclass id of chair category(0 to 14). So , would you please tell me the subclass id of Airplanes and  Guitars?

Thank you very much!

**Comment by eliphatfs** [comment]
Airplanes are 0, and guitars are 27, if my memory serves me correctly. You may have a look at the `labels` field in the ShapeNetCore dataset and visualize the point clouds to verify.
