### ISSUE TITLE
GPU需求和训练时间

### ISSUE THREAD

**Issue by dongfengxijian** [eliphatfs/SkeletonMerger#6]
我想了解一下训练这个对准关键点检测器一般需要显存多少的GPU以及需要训练多长时间？

**Comment by eliphatfs** [comment]
GPU mem requirement depends largely on your batch size. For batch size 1 even 1G suffices. For modern GPU's as NVIDIA 2070 or above it typically requires several hours on one class of ShapeNetCore dataset.

**Comment by dongfengxijian** [comment]
@eliphatfs 你好，我知道有些工作中batch size会影响最终结果，所以我想请问你一下你实验时，使用的GPU情况以及你的训练时间，谢谢。

**Comment by eliphatfs** [comment]
I'm sorry but I cannot remember these details. Any reasonable value should give similar results.

**Comment by dongfengxijian** [comment]
> I'm sorry but I cannot remember these details. Any reasonable value should give similar results.

Thank you for your replying!
